spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles.active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pre-database-1.cguixlvnvxu0.ap-northeast-2.rds.amazonaws.com:3306/MAIN029?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 54255425
  #    url: jdbc:mysql://localhost:3306/MAIN029?serverTimezone=Asia/Seoul
  #    username: root
  #    password: 5425
  output:
    ansi:
      enabled: always
  # JPA ??
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL ?? pretty print
      show-sql: true # SQL ?? ??
      open-in-view: true
      profiles:
        include: database

  # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          clientId: '137375647876-vrq0va0ke0v5joslff4vg9m39bqo752d.apps.googleusercontent.com'
          clientSecret: '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'
          redirect-uri: "http://localhost:8080/login/oauth2/google"
          scope:
            - email
            - profile
        facebook:
          clientId: '725134595852814'
          clientSecret: '5db1ffcd143ff22ce62674d453d30c7b'
          scope:
            - email
            - public_profile
        naver:
          clientId: 'LN5F1_zFJC2Arxy2wkS9'
          clientSecret: 'zH3kq27uOG'
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://localhost:8080/login/oauth2/naver"
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: '8e9ebc53811a31af7c567edfb77bff91'
          clientSecret: 'BGNSrvJx7BfjhL00i1roZ8oXc0QKuAQB'
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://localhost:8080/login/oauth2/kakao"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider ??
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

# cors ??
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key ??
# jwt secret key ??
jwt.secret: "8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds"


# ?? ?? secret Key ? RedirectUri ??
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

# application.yml
#logging:
#  config: classpath:log4j2.yml

